export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const SET_CART_ITEMS = "SET_CART_ITEMS";

// Products
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL    = "FETCH_PRODUCTS_FAIL";

// Orders
export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL    = "FETCH_ORDERS_FAIL";

// Reviews
export const FETCH_REVIEWS_REQUEST  = "FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS  = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAIL     = "FETCH_REVIEWS_FAIL";
export const SUBMIT_REVIEW_REQUEST  = "SUBMIT_REVIEW_REQUEST";
export const SUBMIT_REVIEW_SUCCESS  = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAIL     = "SUBMIT_REVIEW_FAIL";
